#!/bin/bash

# Input CSV file
input_file="./moulins.csv"

# Output .dat file
output_file="./moulin.xy"

# Use awk to extract X and Y coordinates from CSV and save to .dat file
awk -F ',' 'NR>1 {print $1, $2}' "$input_file" > "$output_file"

echo "Coordinates extracted from CSV file and saved to $output_file"
